<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Framework\Escaper;
use Magento\Sales\Block\Order\Recent;
use Magento\Sales\Helper\Reorder;
use Magento\Sales\Model\Order;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper

/** @var Escaper $escaper */
/** @var Recent $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);
/** @var Order[] $orders */
$orders = $block->getOrders();
$count  = count($orders);

$extraActions = [];
if ($extraActionTitleBlocks = $block->getLayout()->getChildBlocks('order-list-extra-action-titles')) {
    foreach ($extraActionTitleBlocks as $alias => $extraActionTitleBlock) {
        $extraActions[$alias] = $extraActionTitleBlock->toHtml();
    }
    $extraActions = array_filter($extraActions, function ($output, string $alias) use ($block): bool {
        return trim($output) && $block->getLayout()->getChildBlock('order-list-extra-action-buttons', $alias);
    }, ARRAY_FILTER_USE_BOTH);
}

?>
<div
    class="block block-dashboard-orders mt-4"
    x-data="{ tabIndex: -1 }"
    style="border: 1px solid #D9D9D9; padding: 0px;"
>
    <div class="block-title order my-4">
        <h2
            id="recentOrders"
            class="text-2xl block"
            @focus="tabIndex = 0;"
            @blur="tabIndex = -1"
            :tabindex="tabIndex"
            style="margin-left: 32px; margin-top: 24px; font-family: Arial; font-weight: 700; font-style: Bold; font-size: 20px; line-height: 32px; letter-spacing: 0%;"
        >Pēdējie pasūtījumi</h2>
    </div>
    <div class="overflow-x-auto">
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0): ?>
            <table
                id="my-orders-table"
                class="w-full"
                aria-labelledby="recentOrders"
                style="border-collapse: collapse; border-spacing: 0; width: 100%;"
            >
                <thead style="background-color: #160F3E;">
                    <tr>
                        <th style="padding: 12px; text-align: left; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif; padding-left: 32px;">
                            PASŪTĪJUMA NR.
                        </th>
                        <th style="padding: 12px; text-align: left; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif;" class="hidden lg:table-cell">
                            DATUMS
                        </th>
                        <th style="padding: 12px; text-align: left; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif;">
                            PASŪTĪTĀJS
                        </th>
                        <th style="padding: 12px; text-align: left; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif;" class="hidden lg:table-cell">
                            SUMMA
                        </th>
                        <th style="padding: 12px; text-align: left; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif;" class="hidden lg:table-cell">
                            STATUSS
                        </th>
                        <th style="padding: 12px; text-align: center; color: white; font-size: 14px; font-weight: 700; font-family: Arial, sans-serif;">
                            VIEW/REORDER
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($orders as $order): ?>
                        <tr style="border-bottom: 1px solid #e5e7eb;">
                            <th
                                id="order<?= $escaper->escapeHtmlAttr($order->getRealOrderId()) ?>"
                                style="padding: 12px; text-align: left; font-weight: normal; color: #E53647; padding-left: 32px;"
                            >
                                <?= $escaper->escapeHtml($order->getRealOrderId()) ?>
                                <p class="lg:hidden text-sm">
                                    <?= $escaper->escapeHtml($block->formatDate($order->getCreatedAt())) ?>
                                </p>
                            </th>
                            <td style="padding: 12px; font-family: Raleway, Arial, sans-serif;" class="hidden lg:table-cell">
                                <?php
                                    $date = $order->getCreatedAt();
                                    $format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
                                    $formatLong = $block->getDateFormat() ?: \IntlDateFormatter::LONG;
                                ?>
                                <span aria-hidden="true">
                                    <?= $escaper->escapeHtmlAttr($block->formatDate($date, $format)); ?>
                                </span>
                                <span class="sr-only">
                                    <?= $escaper->escapeHtml($block->formatDate($date, $formatLong)); ?>
                                </span>
                            </td>
                            <td style="padding: 12px; font-family: Raleway, Arial, sans-serif;">
                                <?= $order->getShippingAddress() ? $escaper->escapeHtml($order->getShippingAddress()->getName()) : '&nbsp;' ?>
                            </td>
                            <td style="padding: 12px; font-family: Raleway, Arial, sans-serif; font-weight: 700; font-size: 14px; line-height: 24px; font-variant-numeric: lining-nums proportional-nums; text-align: left;" class="hidden lg:table-cell">
                                € <?= /* @noEscape */ number_format($order->getGrandTotal(), 2, ',', ' ') ?>
                            </td>
                            <td style="padding: 12px; padding-left: 0px;" class="hidden lg:table-cell">
                                <div class="flex items-center">
                                    <?php
                                        $status = $order->getStatus();
                                        if ($status === 'pending') {
                                            echo '<div style="width: 8px; height: 8px; background-color: #FFC165; border-radius: 50%; margin-right: 8px;"></div>Gaida';
                                        } elseif ($status === 'complete' || $status === 'processing') {
                                            echo '<div style="width: 8px; height: 8px; background-color: #00A887; border-radius: 50%; margin-right: 8px;"></div>Apmaksāts';
                                        } else {
                                            echo '<div style="width: 8px; height: 8px; background-color: #E53647; border-radius: 50%; margin-right: 8px;"></div>Neapmaksāts';
                                        }
                                    ?>
                                </div>
                            </td>
                            <td style="padding: 12px;">
                                <?php // 'received' is an order status added in Magento_AsyncOrder in Adobe Commerce ?>
                                <?php // The condition will always return 'true' in Magento Open Source ?>
                                <?php if ($order->getStatus() !== 'received'): ?>
                                    <div class="flex items-center justify-end" style="padding-right: 32px; gap: 12px;">
                                        <a
                                            href="<?= $escaper->escapeUrl($block->getViewUrl($order)) ?>"
                                            class="inline-block text-sm underline text-secondary-darker"
                                            title="<?= $escaper->escapeHtmlAttr(__('View Order')) ?>"
                                            aria-label="<?= $escaper->escapeHtmlAttr(__('View order') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                                        >
                                            <?= $heroicons->eyeHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                                        </a>
                                        <?php if ($this->helper(Reorder::class)->canReorder($order->getEntityId())): ?>
                                            <?php $formData = json_decode(
                                                $this->helper(PostHelper::class)->getPostData(
                                                    $block->getReorderUrl($order)
                                                ),
                                                true
                                            ) ?>
                                            <form
                                                action="<?= $escaper->escapeUrl($formData['action']) ?>"
                                                method="post"
                                                class="inline-flex items-center"
                                            >
                                                <?= $block->getBlockHtml('formkey'); ?>
                                                <input type="hidden" name="data" value='<?= /* @noEscape */ json_encode($formData['data']) ?>'>
                                                <button
                                                    title="<?= $escaper->escapeHtmlAttr(__('Reorder')) ?>"
                                                    type="submit"
                                                    class="inline-block text-sm text-secondary-darker"
                                                    aria-label="<?= $escaper->escapeHtmlAttr(__('Reorder') . ' ' . ltrim($order->getRealOrderId(), '0')) ?>"
                                                >
                                                    <?= $heroicons->refreshHtml('', 24, 24, ['aria-hidden' => 'true']) ?>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?= $heroicons->refreshHtml('text-gray-300', 24, 24, ['aria-hidden' => 'true']) ?>
                                        <?php endif ?>
                                        <?php foreach (array_keys($extraActions) as $alias): ?>
                                            <?php $button = $block->getLayout()->getChildBlock('order-list-extra-action-buttons', $alias) ?>
                                            <?= $button->assign('order', $order)->setData('order', $order)->toHtml() ?>
                                        <?php endforeach; ?>
                                    </div>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        <?php else: ?>
            <div class="message info empty">
                <span><?= $escaper->escapeHtml(__('You have placed no orders.')) ?></span>
            </div>
        <?php endif; ?>
        
        <!-- View All Button below table -->
        <?php if ($count > 0): ?>
            <div class="mt-6 text-left">
                <a
                    class="action view inline-flex items-center justify-center text-white font-bold no-underline"
                    href="<?= $escaper->escapeUrl($block->getUrl('sales/order/history')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('View all orders')) ?>"
                    style="width: 167px; height: 48px; background-color: #E53848; font-family: Arial; font-weight: 700; font-size: 14px; line-height: 24px; margin-left: 32px; margin-bottom: 24px;"
                >SKATĪT VISU</a>
            </div>
        <?php endif; ?>
    </div>
</div>
