<?php
/**
 * Custom crosssell products template displayed as "Related Products"
 */
/** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
/** @var \Magento\Framework\Escaper $escaper */

$items = $block->getItems();

$exist = count($items);
?>


<?php if ($exist): ?>
<div class="block related" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}'>
    <div class="block-title title">
        <strong id="block-related-heading" role="heading" aria-level="2">
            <?= $escaper->escapeHtml(__('Related Products')) ?>
        </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-related-heading">
        <div class="products wrapper grid products-grid products-related">
            <ol class="products list items product-items">
                <?php foreach ($items as $_item): ?>
                <li class="item product product-item" id="product-item_<?= /* @noEscape */ $_item->getId() ?>">
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                        <?= $block->getImage($_item, 'related_products_list')->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <div class="product-item-name-and-reviews">
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   title="<?= $escaper->escapeHtmlAttr($_item->getName()) ?>"
                                   href="<?= $escaper->escapeUrl($block->getProductUrl($_item)) ?>">
                                    <?= $escaper->escapeHtml($_item->getName()) ?>
                                </a>
                            </strong>

                            <?= $block->getReviewsSummaryHtml($_item, \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW) ?>
                        </div>

                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                    </div>
                    
                    <div class="product actions product-item-actions">
                        <?php if ($_item->isSaleable()): ?>
                        <!-- "Add to Cart" button for related products -->
                        <?php if (!$_item->isComposite() && !$_item->getRequiredOptions()): ?>
                        <form data-role="tocart-form" 
                              data-product-sku="<?= $escaper->escapeHtmlAttr($_item->getSku()) ?>" 
                              action="<?= $escaper->escapeUrl($block->getAddToCartUrl($_item)) ?>" 
                              method="post">
                            <input type="hidden" name="product" value="<?= $escaper->escapeHtmlAttr($_item->getId()) ?>" />
                            <?= $block->getBlockHtml('formkey') ?>
                            <button type="submit" 
                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>" 
                                    class="action primary tocart">
                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                            </button>
                        </form>
                        <?php endif; ?>
                        <?php endif; ?>
                    </div>
                </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
</div>
<?php endif; ?> 