<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Magento\Framework\View\Element\Html\Links;
use Magento\Framework\Escaper;

/** @var Links $block */
/** @var Escaper $escaper */
?>
<div class="width: 400px; height: 660px; background-color: #F2F2F2;">
    <div class="content">
        <nav class="account-nav" aria-label="<?= $escaper->escapeHtmlAttr(__('Mans profils')) ?>">
            <ul class="nav items m-0 p-0 list-none">
                <?= $block->getChildHtml() ?>
            </ul>
        </nav>
    </div>
</div>

<style>

/* Navigacijas stailings */
.account-nav .nav.items li {
    @apply width: 400px; height: 60px; display: flex; align-items: center; padding-left: 40px; padding-right: 40px; margin: 0; list-style: none;
    background-color: #F2F2F2;
    font-family: Arial, sans-serif;
}

.account-nav .nav.items li.current {
    background-color: #F2F2F2;
    background-image: linear-gradient(90deg, rgba(229, 54, 71, 0.05) 0%, rgba(229, 54, 71, 0) 100%);
    border-left: 6px solid #E53647;
}

.account-nav .nav.items li.current strong {
    text-decoration: none;
}
</style>


